sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeaway
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t81U4hLZdzQRnWDawDb
    access-key-secret: 6BkKEoeN7YcIaDaCUExDLB1VSN8o65
    bucket-name: sky-takeaway-pic